spring:
  profiles:
    active: local
  thymeleaf:
    prefix : classpath:templates/
    suffix : .html
    cache : false
  config:
    import: apikey.yml  
logging:
    level:
      root: info
      com.openai: DEBUG
    file:
      name: /home/users/djna/jar/log/spring-gpt.log
    logback: 
      rollingpolicy:
        file-name-pattern: Log-%d{yyyy-MM-dd}.%i.log
        clean-history-on-start: true
        total-size-cap: 100MB
        max-history: 30
        max-file-size: 100MB
---
spring:
  config:
    activate:
      on-profile: local
  devtools:
    restart:
      enabled: true
server:
  title: spring-gpt-local
  port : 8080

---
spring:
  config:
    activate:
      on-profile: prod
  devtools:
    restart:
      enabled: false
server:
  title: spring-gpt-prod
  port : 8081