name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Build with Gradle
        run: ./gradlew build

      - name: Deploy to NHN Cloud
        uses: DongJu-Na/spring-gpt@v2.5.2
        with:
          version: "1.0.0"
          path: "build/libs/*.jar"
          command: "java -jar"
          deploy-env: "production"
          api-key: ${{ secrets.NHNCLOUD_API_KEY }}
