name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
     # - name: Set up JDK 17
     #   uses: actions/setup-java@v2
     #   with:
     #     java-version: 17

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.NHN_HOST }}
          username  : ${{ secrets.NHN_USERNAME }}
          password : ${{ secrets.NHN_PASSWORD }}
          script: |
           cd /ndj/
           wget https://github.com/DongJu-Na/spring-gpt/archive/refs/heads/main.zip

      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Build with Gradle
        run: ./gradlew build