name Build and Deploy

on
  push
    branches
      - main
  pull_request
    branches
      - main

jobs
  build-and-deploy
    runs-on ubuntu-latest

    steps
      - name Checkout code
        uses actionscheckout@v2

      - name Set up JDK 17
        uses actionssetup-java@v2
        with
          java-version 17

      - name Build with Gradle
        run .gradlew build

      - name Deploy to NHN Cloud
        uses nhntui-gradle-plugin-action@v2.5.2
        with
          version 1.0.0
          path buildlibs.jar
          command java -jar
          deploy-env production
          api-key ${{ secrets.NHNCLOUD_API_KEY }}
