name: Deploy to NHN Cloud

on:
  push:
    branches: [ main ]

env:
  NHN_CLOUD_USERNAME: ${{ secrets.NHN_USERNAME }}
  NHN_CLOUD_PASSWORD: ${{ secrets.NHN_PASSWORD }}
  APP_NAME: spring-gpt
  APP_TYPE: spring-boot
  APP_PORT: 8080

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: touch ./src/main/resources/apikey.yml
      - run: echo "${{ secrets.GPT_KEY }}" > ./src/main/resources/apikey.yml
      - run: cat ./src/main/resources/apikey.yml

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17

      - name: Grant execution permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-test

      - name: Install NHN Cloud CLI
        run: |
          curl -sL https://cli.ncloud.com/install.sh | bash
          export PATH=$PATH:/root/bin

      - name: Deploy to NHN Cloud
        run: |
          ncloud configure set access_key_id $NHN_CLOUD_USERNAME
          ncloud configure set secret_access_key $NHN_CLOUD_PASSWORD
          ncloud app deploy $APP_NAME --type $APP_TYPE --port $APP_PORT --artifact build/libs/*.jar