name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Build with Gradle
        run: ./gradlew build

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.NHN_HOST }}
          username  : ${{ secrets.NHN_USERNAME }}
          password : ${{ secrets.NHN_PASSWORD }}
           script: |
           cd /ndj/
           git fetch --all
           git pull origin main
          
